server:
  port: 8080

spring:
  datasource:
    # ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: 'jdbc:h2:mem:testdb1;DB_CLOSE_DELAY=-1'
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  sql:
    init:
      # ALWAYS 始终, EMBEDDED仅嵌入式, NEVER 从不 
      mode: always
      separator: ;
      encoding: UTF-8
      # 数据脚本平台: 模式-${Platform}; 默认是schema和data,当设置h2时加载schema,data, schema-h2和data-h2这4个sql;另:当设置schema和data脚本的时候, platform失效
      platform: h2
      #schema-locations: classpath:db/schema.sql
      #data-locations: classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    sql: debug
    org.springframework: info
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.mybatis: debug
    org.mybatis.spring: debug
    org.apache.ibatis.logging.LogFactory: debug
    com.example.demo: DEBUG
