spring:
  datasource:
    # ;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: 'jdbc:h2:mem:testdb1;DB_CLOSE_DELAY=-1'
    username: sa
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.springframework: info
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.mybatis: debug
    org.mybatis.spring: debug
    org.apache.ibatis.logging.LogFactory: debug
    com.example.demo: DEBUG
